[package]
name = "llm"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { workspace = true}
burn-dataset = "0.18.0"
jsonl = "4.0.1"
serde = { workspace = true }
serde_json = "1.0"
anyhow = "1.0"
rand = "0.8"
tempfile = "3.0"